### PR TITLE
Add TCK for specification

### PR DESCRIPTION
**Pull request by ericbottard**
Opening a draft PR for anyone to play with if interested.

Requires a `tck.toml` file in the current directory, similar to this:
```toml
[images]
upper = "docker.io/ericbottard/upper"
```

(the TCK currently uses a single "function").

Sadly, the first test (verifying usage of $PORT) is going to be difficult to test, as buildpacks don't see regular docker ENV VARS

### CODE REVIEW

**Review by glyn — COMMENTED** [review]
A README starting with an example of how to run the TCK against a particular invoker would take out some of the guesswork.

**Comment by ericbottard** [comment]
> A README starting with an example of how to run the TCK against a particular invoker would take out some of the guesswork.

This will come, of course. Given the RFC and the description of this PR, do you need more help now?

**Comment by glyn** [comment]
> > A README starting with an example of how to run the TCK against a particular invoker would take out some of the guesswork.
> 
> This will come, of course. Given the RFC and the description of this PR, do you need more help now?

Yes, please. Just some terminal history showing how you run the TCK against one of the simpler invokers would probably be sufficient.

**Comment by ericbottard** [comment]
> Yes, please. Just some terminal history showing how you run the TCK against one of the simpler invokers would probably be sufficient.

As the RFC states, the TCK doesn't really run against an invoker __per se__ but against a (function) built image.
So, just craft a tck.toml file somewhere, containing
```toml
[images]
upper = "docker.io/glynnormington/upper"
```
and run `./tck` (which you built from the main.go in this repo) and you  should be good.

I'm working on adding java and node samples for functions that the TCK is going to expect, FYI

**Comment by glyn** [comment]
Thanks Eric. I was hoping there was some hacky way to run the invoker+function locally and try the TCK against it, but fair enough.

**Pull request closed without merging**
